title: "lavkazoloto — одни из лучших ювелирных украшений"

exclude:
  - Gemfile
  - Gemfile.lock
  - bower.json
  - config.rb
  - .git
  - .bowerrc
  - README.md
gems:
  - jekyll-assets

assets:
  baseurl: assets/
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/bower_components/bootstrap-sass-twbs/assets/stylesheets
    - _assets/bower_components/bootstrap-sass-twbs/assets/fonts
    - _assets/bower_components
  js_compressor:  uglifier
  css_compressor: sass
  gzip: false

host: 0.0.0.0
